---
# Systemd
- name: '[systemd] Generate systemd dnscrypt-proxy.socket unit'
  template:
    src: systemd/dnscrypt-proxy.socket.j2
    dest: /etc/systemd/system/dnscrypt-proxy.socket
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart dnscrypt-proxy.socket systemd unit
  tags:
  - dnscrypt
  - dnscrypt_systemd

- name: '[systemd] Generate systemd dnscrypt-proxy.service unit'
  template:
    src: systemd/dnscrypt-proxy.service.j2
    dest: /etc/systemd/system/dnscrypt-proxy.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart dnscrypt-proxy.socket systemd unit
  tags:
  - dnscrypt
  - dnscrypt_systemd
...
